### ISSUE TITLE
Type of ofAction mismatch after upgrade to 2.0.5

### ISSUE THREAD

**Issue by sandangel** [amcdnl/ngrx-actions#12]
After upgrading to 2.0.5, ofAction has error: Argument of type 'typeof LoginAction' is not assignable to parameter of type 'new () => Action'.

with action class: 

```ts
export class LoginAction implements Action {
  readonly type = '[Auth] Login';
  constructor(public payload: { email: string; password: string }) {}
}

```
This is because LoginAction class constructor has 1 parameter while type new () => Action has none.

**Comment by amcdnl** [comment]
@albyrock87 - Can you address this?

**Comment by albyrock87** [comment]
I'm really sorry for this bug.. the unit test was not exaustive so I didn't catch this issue.
