### ISSUE TITLE
Better infer type checking ofAction

### ISSUE THREAD

**Issue by sandangel** [amcdnl/ngrx-actions#17]
Can you consider changing return type OperatorFunction<Action, Action> to OperatorFunction<Action, T>?

https://github.com/amcdnl/ngrx-actions/blob/6ed55d5d9d477b9557afe42021c68ab502a39f66/src/of-action.ts#L10

Then user could use like this

```ts
@Effect()
getFooBar$ = this.actions$.pipe(
    ofAction<GetFoo | GetBar>(
      GetFoo, GetBar
    ),
    map(action /* action has infer type GetFoo | GetBar */ => { ... })
```

**Comment by albyrock87** [comment]
You always have good ideas :1st_place_medal: 
Thank you
