### ISSUE TITLE
@Select decorator improvement

### ISSUE THREAD

**Issue by eomusoru** [amcdnl/ngrx-actions#36]
Hey guys!

I'm using @Select decorator for ngrx-actions and it works pretty fine. Although, when the app and the store are pretty big, it's always very often the probability that the selector which is actually a string, to be wrong types.

Ex:
let's suppose we  have: @Select("myStore.myPieceOfStore") public pieceOfStore$: Observable<any>;

It's very often a probability like 'myStore.myPieceOfStore' string to be wrong typed and we are not going to have any errors to tell us this. 

Do you think we improve this? 

Thanks!

**Comment by amcdnl** [comment]
You can use a fn like: `@Select((state: AppState) => state.foo.bar)`
