### ISSUE TITLE
Can it be used with redux?

### ISSUE THREAD

**Issue by BeaveArony** [amcdnl/ngrx-actions#42]
Hi Austin,

great work trying to reduce boilerplate code!
One of the projects I'm working on is still AngularJS with typescript, redux, redux-observables, reselect...

Would you maybe consider making a version for plain redux? Actions should also be POJOs instead of classes I think.

It might be enough to educate me about how to do it in a blog post or so. :)

I think that once we migrate to angular we will stick with redux and not switch to ngrx to use all the awesome middleware and tools from the redux-community (redux-persist, redux-offline...). ng2-redux would be also be a good choice I think.

Cheers,
Michael

**Comment by amcdnl** [comment]
In the first implementation it would have worked but now its pretty coupled to ngrx. Sorry :(
