### ISSUE TITLE
RxJs 6 - Property 'pipe' does not exist in type 'Actions<Action>'

### ISSUE THREAD

**Issue by gregkopp** [amcdnl/ngrx-actions#50]
I am looking at upgrading out project to RxJs 6. Going through the code, I have made all changes that were having compile issues. However, every single Effect I have is showing the same error. Prior to RxJs 6 (up to and including 5.5.10), all worked as expected.

```typescript
@Injectable()
export class WidgetSearchEffects {
    @Effect()
    detectWidgetDataRequested$ = this.actions$.pipe(
        ofAction(OnWidgetDataRequested),
        mergeMap((action: OnWidgetDataRequested) => this.widgetSearchService.searchById(action.payload)
          .pipe(map((data: WidgetSearchResult) => WidgetSearchActions.onWidgetDataReceipt(data)))),
        catchError(error => this.onError(error))
    );

    constructor(
        private actions$: Actions,
        private widgetSearchService: WidgetSearchService
    ) {}

    private onError = (error: Error) => {
        return of(WidgetSearchActions.serverError(error));
    }
}
```

I get the same error on every effect:

```
Property 'pipe' does not exist on type 'Actions<Action>'.
```

Any ideas of where I went wrong or is this a compatibility issue with ngrx-actions and RxJs 6

**Comment by bretuobay** [comment]
This was closed by opener without any explanation. Can you please explain how you solved this? Thank you.
