### ISSUE TITLE
Question: any ETA for a ng6 compatible version?

### ISSUE THREAD

**Issue by jotatoledo** [amcdnl/ngrx-actions#54]
As the title says, currently ngrx-actions is not ng6 compatible (withouth rxjs-compat). 

Is there any ETA for a new release?

**Comment by kmiskiewicz** [comment]
+1 :-)

**Comment by aldokocha** [comment]
+1

**Comment by jotatoledo** [comment]
Please upvote instead of adding +1

**Comment by jotatoledo** [comment]
cc @amcdnl let me know if I can contribute in some way

**Comment by amcdnl** [comment]
done. see 4.0
