### ISSUE TITLE
Cannot find module 'ngrx-actions'

### ISSUE THREAD

**Issue by thaoula** [amcdnl/ngrx-actions#55]
Hi Guys,

I just updated to version 4 and now I am unable to build the project using Angular CLI 6.0.7

I get the following error - Cannot find module 'ngrx-actions'

I have deleted node_module and downloaded everything again. Reverting back to v3.1.6 allows me to build again.

I am using Angular 6, CLI 6.0.7 and NGRX 6.0.1

Regards,
Tarek

**Comment by aldokocha** [comment]
Same issue

**Comment by MarkoCen** [comment]
Same here, currently work around...
```
import { Select } from 'ngrx-actions/dist/select'
```

**Comment by thaoula** [comment]
Hi @amcdnl,

I know you are working on NGXS and it looks really awesome .. i wish we can use it. However, at this stage in our development cycle we are not in a position to migrate our app to NGXS even though I would like too.

So my question, which is based on the time this issue has been open. Is this library now dead .. and we should make plans to migrate back to standard NGRX (hoping you don't say yes)?

Regards,
Tarek

**Comment by gregkopp** [comment]
Any chance we can get this simple fix implemented soon?

**Comment by JanLoebel** [comment]
Hey there, please merge #57 - it looks like it works great!

**Comment by ruimserrano** [comment]
hi,
my team did a work around around this issue

we add a path in the ts.config:
````json
"paths": {
   ...
   "ngrx-actions": [ "../node_modules/ngrx-actions/dist" ]
}
````

then when #57 gets merged, you just need to delete that, no other changes in the code required

**Comment by gregkopp** [comment]
@ruimserrano For this to work with webpack, it looks like I will need "tsconfig-paths-webpack-plugin". Or is there a better way?

**Comment by ruimserrano** [comment]
@gregkopp works for me in a angular.cli project, in a webpack project - non angular cli i dont know.

here is my full tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@app/*": [
        "app/*"
      ],
      "@env/*": [
        "environments/*"
      ],
      "@testhelpers/*": [
        "testhelpers/*"
      ],
      "@core/*": [
        "app/core/*"
      ],
      "ngrx-actions": [
        "../node_modules/ngrx-actions/dist"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "coverage"
  ]
}
```
