### ISSUE TITLE
No type checking for the @Select decorator

### ISSUE THREAD

**Issue by ocombe** [amcdnl/ngrx-actions#6]
When doing something like that with ngrx:

```ts
files$: Observable<I18nFile[]> = this.store.select(getI18nFilesEntities);
```

I get a type check that the store will return something of type `I18nFile[]`.

But if I change it to that:

```ts
@Select('i18nFiles.entities') files$: Observable<I18nFile[]>;
```

It doesn't type check that it's of type `I18nFile[]`.

I'm not sure if it's possible to type check with decorators, but that would be nice.

**Comment by ocombe** [comment]
Never mind, I discovered that you can do that with the store select, this decorator is actually not useful.

This works and gives type checking
```ts
files$: Observable<I18nFile[]> = this.store.select('i18nFiles', 'entities');
```

**Comment by amcdnl** [comment]
Reference: https://github.com/Microsoft/TypeScript/issues/4881
